In [2]:
import numpy as np

In [3]:
n1 = np.array([1,2,3])
n2 = np.array([4,5,6])

In [4]:
np.add(n1,n2)

array([5, 7, 9])

In [5]:
n1 + n2

array([5, 7, 9])

In [6]:
n1 - n2

array([-3, -3, -3])

In [7]:
n1 * n2

array([ 4, 10, 18])

In [8]:
n1 ** n2

array([  1,  32, 729])

In [9]:
n1/n2

array([0.25, 0.4 , 0.5 ])

In [10]:
n1 < n2

array([ True,  True,  True])

In [17]:
n3 = np.array([[1,2],[3,4]])
n4 = np.array([[5,6],[7,8]])

In [18]:
n3 + n4

array([[ 6,  8],
       [10, 12]])

In [19]:
n3 & n4

array([[1, 2],
       [3, 0]])

In [20]:
n3 | n4

array([[ 5,  6],
       [ 7, 12]])

In [22]:
n3 * 10

array([[10, 20],
       [30, 40]])

In [23]:
n3 = np.array([[1,2],[3,4]])
n4 = np.array([[5,6],[7,8]])

In [25]:
np.matmul(n3,n4)

array([[19, 22],
       [43, 50]])

In [26]:
np.dot(n3,n4)

array([[19, 22],
       [43, 50]])

In [27]:
np.sqrt(n3)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [28]:
n3 ** 0.5

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [32]:
n3

array([[1, 2],
       [3, 4]])

In [31]:
n3.flatten('C')

array([1, 2, 3, 4])

In [33]:
n3.flatten('F')

array([1, 3, 2, 4])

In [39]:
day1 = np.datetime64('2022-01-01')
print(day1)

2022-01-01


In [40]:
type(day1)

numpy.datetime64

In [41]:
day2 = np.datetime64('2022-04-01')
print(day2)

2022-04-01


In [43]:
days = day2 - day1
print(days)

90 days


In [44]:
print(np.datetime64('2022-04-10') - np.datetime64('2022-04-01'))

9 days


In [48]:
print(np.datetime64('2022-04-01') + np.timedelta64(6,'D'))

2022-04-07


In [49]:
print(np.datetime64('Today'))

2022-04-10


In [50]:
n3

array([[1, 2],
       [3, 4]])

In [51]:
n4

array([[5, 6],
       [7, 8]])

In [53]:
np.hstack([n3,n4])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [54]:
np.vstack([n3,n4])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [55]:
np.dstack([n3,n4])

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [56]:
np.column_stack([n3,n4])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [57]:
np.row_stack([n3,n4])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [64]:
np.append(n3,n4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [65]:
np.append(n3,n4,axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
np.append(n3,n4,axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [67]:
np.append(n3,n4,axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [71]:
np.concatenate((n3,n4),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [72]:
np.concatenate((n3,n4),axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [90]:
n5 = np.arange(1,19).reshape(6,3)

In [91]:
n5

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [101]:
np.array_split(n5,len(n5))

[array([[1, 2, 3]]),
 array([[4, 5, 6]]),
 array([[7, 8, 9]]),
 array([[10, 11, 12]]),
 array([[13, 14, 15]]),
 array([[16, 17, 18]])]

In [93]:
np.hsplit(n5,3)

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]), array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]), array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [96]:
np.vsplit(n5,2)

[array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]), array([[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]])]

In [99]:
# have to check
# np.hsplit(n5,np.array([1,1]))