In [1]:
import numpy as np

In [3]:
j = np.array([1,2,3])
j

array([1, 2, 3])

In [4]:
type(j[0])

numpy.int32

In [5]:
j = np.array([1.5,2,3])
j

array([1.5, 2. , 3. ])

In [6]:
type(j[0])

numpy.float64

In [7]:
s = np.array([1,2,3], dtype = int)
s

array([1, 2, 3])

In [8]:
s.ndim

1

In [9]:
arr = np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [10]:
arr.reshape((2,2))

array([[1, 2],
       [3, 4]])

In [11]:
arr.ndim

1

In [12]:
arr2 = np.array([[1,2,3,4]])
arr2

array([[1, 2, 3, 4]])

In [13]:
arr2.ndim

2

In [15]:
arr3 = np.array([1,2,3,4,5,6,7,8,9]).reshape((3,3))
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
arr4 = np.identity(3)
arr4

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr5 =np.full([5,5],5)
arr5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [24]:
arr6 = np.arange(start = 0, stop = 1000, step = 2)
arr6

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102,
       104, 106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128,
       130, 132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154,
       156, 158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180,
       182, 184, 186, 188, 190, 192, 194, 196, 198, 200, 202, 204, 206,
       208, 210, 212, 214, 216, 218, 220, 222, 224, 226, 228, 230, 232,
       234, 236, 238, 240, 242, 244, 246, 248, 250, 252, 254, 256, 258,
       260, 262, 264, 266, 268, 270, 272, 274, 276, 278, 280, 282, 284,
       286, 288, 290, 292, 294, 296, 298, 300, 302, 304, 306, 308, 310,
       312, 314, 316, 318, 320, 322, 324, 326, 328, 330, 332, 334, 336,
       338, 340, 342, 344, 346, 348, 350, 352, 354, 356, 358, 36

In [28]:
arr22 = np.append(arr2, 10)

In [29]:
arr22

array([ 1,  2,  3,  4, 10])

In [26]:
np.insert(arr2, 2, 10)

array([ 1,  2, 10,  3,  4])

In [27]:
arr2

array([[1, 2, 3, 4]])

In [30]:
np.delete(arr2, 3)
arr2

array([[1, 2, 3, 4]])

In [31]:
np.delete(arr2, 3)

array([1, 2, 3])

# ===========================Day 2=============================

In [3]:
arr1 = np.array([1,2,3])

In [4]:
arr1.min()

1

In [5]:
arr1.max()

3

In [10]:
np.median(arr1)

2.0

In [11]:
np.min(arr1)

1

In [12]:
arr2= np.array([2, 4,6])
arr2

array([2, 4, 6])

In [15]:
arr1

array([1, 2, 3])

In [13]:
result = np.add(arr1, arr2)

In [14]:
result

array([3, 6, 9])

In [17]:
result2 = np.sum([arr1, arr2])
result2

18

In [19]:
result3 = np.sum([arr1, arr2], axis = 1)
result3

array([ 6, 12])

In [21]:
arr1

array([1, 2, 3])

In [22]:
arr2

array([2, 4, 6])

In [20]:
multiply = np.multiply(arr1, arr2)
multiply

array([ 2,  8, 18])

In [23]:
divide = np.divide(arr1, arr2)
divide

array([0.5, 0.5, 0.5])

In [24]:
power = np.power(arr1, arr2)
power

array([  1,  16, 729], dtype=int32)

In [25]:
power2 = np.power(arr2, arr1)
power2

array([  2,  16, 216], dtype=int32)

In [29]:
sample = np.random.randint(0, 100, (5,5))
sample

array([[ 6,  4, 75,  7, 22],
       [48, 88, 22, 65,  3],
       [82,  3, 80,  2, 97],
       [82, 59,  1, 99, 93],
       [75, 96, 66, 60, 33]])

In [31]:
arr2[:2]

array([2, 4])

In [32]:
arr2[-2:]

array([4, 6])

In [33]:
arr2

array([2, 4, 6])

In [34]:
sample2 = np.random.randint(0, 100, (5,5))
sample2

array([[ 3,  8, 90, 30, 93],
       [35, 54, 82, 64, 22],
       [33, 18, 21, 89, 17],
       [49, 55, 84,  2, 24],
       [ 7, 51, 55, 24, 65]])

In [35]:
sample2[1:]

array([[35, 54, 82, 64, 22],
       [33, 18, 21, 89, 17],
       [49, 55, 84,  2, 24],
       [ 7, 51, 55, 24, 65]])

In [36]:
np.subtract(sample,sample2)

array([[  3,  -4, -15, -23, -71],
       [ 13,  34, -60,   1, -19],
       [ 49, -15,  59, -87,  80],
       [ 33,   4, -83,  97,  69],
       [ 68,  45,  11,  36, -32]])

In [37]:
round2 = np.array([5.333, 2])
round2

array([5.333, 2.   ])

In [42]:
res = np.around(round2, 2)
res

array([5.33, 2.  ])

In [39]:
res = np.around(5.633, 2)
res

5.63

In [43]:
res4 = np.trunc([-5.633, 2.77])
res4

array([-5.,  2.])

In [44]:
res5 = np.floor([-5.633, 2.77])
res5

array([-6.,  2.])