In [1]:
import numpy as np

# 1

In [111]:
arr1= np.array([1,2,3,4.4,6.6])
print(arr1)

[1.  2.  3.  4.4 6.6]


In [3]:
type(arr1[0])

numpy.float64

In [4]:
arr2 = np.array([1,2,3,4,6,], dtype = int)
print(arr2)

[1 2 3 4 6]


In [5]:
type(arr2[0])

numpy.int32

In [6]:
arr3 = np.array([1,2,3,4,6,], dtype = float)
print(arr3)

[1. 2. 3. 4. 6.]


In [7]:
type(arr3[0])

numpy.float64

# 2

In [8]:
# 2. Create numpy arrays that have zero, one, two, three, Four dimensions respectively.
#Also, print the shape and dimensions of the numpy arrays created above.

In [113]:
arr1 = np.array(10) #scaler
print(arr1)
print(arr1.ndim)
print(arr1.shape)

10
0
()


In [10]:
arr2 = np.array([1,2,3,4,5])
print(arr2.ndim)
print(arr2.shape)

1
(5,)


In [11]:
arr3 = np.array([[1,2,3],[4,5,6]])
print(arr3)
print(arr3.ndim)
print(arr3.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [12]:
arr4 = np.array([[[1,2,3],[4,5,6]]])
print(arr4)
print(arr4.ndim)
print(arr4.shape)

[[[1 2 3]
  [4 5 6]]]
3
(1, 2, 3)


In [13]:
arr5 = np.array([[[[1,2,3],[4,5,6]]]])
print(arr5)
print(arr5.ndim)
print(arr5.shape)

[[[[1 2 3]
   [4 5 6]]]]
4
(1, 1, 2, 3)


In [14]:
A = np.arange(8).reshape(2, 2, 2)
A

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [15]:
# 3. Create a 2x3, 3x3, and 4x4 identity matrix using numpy.

In [16]:
arr1 = np.identity(2)
print(arr1)

[[1. 0.]
 [0. 1.]]


In [17]:
arr1 = np.identity(2, dtype=int)
print(arr1)

[[1 0]
 [0 1]]


In [18]:
arr2 = np.identity(3)
print(arr2)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [19]:
# 4. Create a numpy array with shape 2x5 that has all the elements as zero.

In [20]:
arr1 = np.zeros([2,5])
print(arr1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [115]:
arr1 = np.full([3,5],5)
print(arr1)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [22]:
#6. Create a numpy array with random integers in the range 0-100, and the sample size
#should be 25.

In [23]:
arr1 = np.random.randint(0, 100, size=25)
print(arr1)

[47  4 45 93  1 79 47 60 24 44 71 65  1  6 99 18  7 95 98 69 87  0 59 32
 29]


In [24]:
arr1.reshape(5,5)

array([[47,  4, 45, 93,  1],
       [79, 47, 60, 24, 44],
       [71, 65,  1,  6, 99],
       [18,  7, 95, 98, 69],
       [87,  0, 59, 32, 29]])

In [25]:
# 7. Create a numpy array with a shape 3x3 that has all elements as 1.

In [26]:
arr1 = np.full((3,3),1)
arr1

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [27]:
# 8. Create a numpy array in the shape 2x3 with random integers in the range 0-100.
#Reshape the array in the shape 3x2 and print the updated shape of the resultant array.

In [28]:
arr1 = np.random.randint(0,100,(2,3)).reshape(3,2)
print(arr1)

[[28 13]
 [82 90]
 [72 75]]


In [29]:
#9. Create a numpy array, with the range 0-1000, with and step 2. Perform thefollowing
#operations on the same.
#a. Print the first ten elements of the array.
#b. Print the last ten elements of the array
#c. Print the elements from the indexes 10-25
#d. Print the element at the index 22
#e. Print the array using negative indexing.
#f. Print the last ten elements of the array, using negative indexing.

In [30]:
arr1 = np.arange(start = 0, stop = 1000, step = 2)
print(arr1)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106
 108 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142
 144 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178
 180 182 184 186 188 190 192 194 196 198 200 202 204 206 208 210 212 214
 216 218 220 222 224 226 228 230 232 234 236 238 240 242 244 246 248 250
 252 254 256 258 260 262 264 266 268 270 272 274 276 278 280 282 284 286
 288 290 292 294 296 298 300 302 304 306 308 310 312 314 316 318 320 322
 324 326 328 330 332 334 336 338 340 342 344 346 348 350 352 354 356 358
 360 362 364 366 368 370 372 374 376 378 380 382 384 386 388 390 392 394
 396 398 400 402 404 406 408 410 412 414 416 418 420 422 424 426 428 430
 432 434 436 438 440 442 444 446 448 450 452 454 456 458 460 462 464 466
 468 470 472 474 476 478 480 482 484 486 488 490 49

In [31]:
#b. Print the last ten elements of the array
print(arr1[-10:])


[980 982 984 986 988 990 992 994 996 998]


In [32]:
#c. Print the elements from the indexes 10-25
print(arr1[10:26])

[20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [33]:
#e. Print the array using negative indexing.
print(arr1[-22:-7])

[956 958 960 962 964 966 968 970 972 974 976 978 980 982 984]


In [34]:
#10. Given a numpy array that has values = [1,2,3,4,5]. Perform the following operations.
#a. Insert the element 6 at the end of the array.
#b. Insert the element 10 at the beginning of the array.
#c. Insert the element 30, before 4.
#d. Update the element 5 as 50.
#e. Delete the element 50 in the updated array.
#f. Create a function to search for the element 30.
#g. Sort the array in ascending order.

In [122]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [123]:
#a. Insert the element 6 at the end of the array.
arr1 = np.append(arr1,6)
arr1

array([1, 2, 3, 4, 5, 6])

In [124]:
arr1 = np.insert(arr1,0,10)
arr1

array([10,  1,  2,  3,  4,  5,  6])

In [127]:
arr1[6] = 50
print(arr1)

[10  1  2  3  4  5 50]


In [128]:
#wow

j = np.where(arr1 == 50)[0][0]
j

6

In [40]:
jp = np.where(arr1 == 50)
jp

(array([6], dtype=int64),)

In [41]:
type(jp)

tuple

In [129]:
#e. Delete the element 50 in the updated array.
arr1 = np.delete(arr1, 6])
print(arr1)

[10  1  2  3  4  5]


In [43]:
#f. Create a function to search for the element 30.
for i in arr1:
    if i == 10:
        print(i)

10


In [44]:
#g. Sort the array in ascending order.
print(np.sort(arr1))
arr2 = np.sort(arr1)
arr2

[ 1  2  3  4  5 10]


array([ 1,  2,  3,  4,  5, 10])

In [45]:
np.searchsorted(arr2, 5)

4

# --------------------------------------------------

In [116]:
arr2D = np.array([[11 ,12, 13, 11],
                  [21, 22, 23, 24],
                  [31, 32, 33, 34]])
arr2D[2,3] = 100
arr2D

array([[ 11,  12,  13,  11],
       [ 21,  22,  23,  24],
       [ 31,  32,  33, 100]])

In [117]:
arr2D[arr2D > 10] = 100
arr2D

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

# =====================================================

# Hands on 2

In [46]:
'''1. Given two numpy arrays A and B that have values [1,2,3,4] and [5,6,7,8] respectively.
Perform the following operations.
a. Add the two arrays
b. Subtract the two arrays
c. Multiply the two arrays:
i. With 5
ii. With each other.
d. Divide the two arrays:
i. By 2
ii. Divide A with B
iii. Divide B with A.'''

'1. Given two numpy arrays A and B that have values [1,2,3,4] and [5,6,7,8] respectively.\nPerform the following operations.\na. Add the two arrays\nb. Subtract the two arrays\nc. Multiply the two arrays:\ni. With 5\nii. With each other.\nd. Divide the two arrays:\ni. By 2\nii. Divide A with B\niii. Divide B with A.'

In [119]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])
arr1, arr2

(array([1, 2, 3, 4]), array([5, 6, 7, 8]))

In [120]:
arr1 + arr2

array([ 6,  8, 10, 12])

In [48]:
#a. Add the two arrays

In [121]:
res = np.add(arr1, arr2)
res

array([ 6,  8, 10, 12])

In [50]:
res = np.sum([arr1, arr2])
res

36

In [51]:
res = np.sum([arr1, arr2], axis = 1)
res

array([10, 26])

In [52]:
res = np.sum([arr1, arr2], axis = 0)
res

array([ 6,  8, 10, 12])

In [53]:
res2 = np.subtract(arr1, arr2)
res2

array([-4, -4, -4, -4])

In [54]:
# Multiply the two arrays:
# i. With 5
# ii. With each other.

In [55]:
res3 = np.multiply(arr1, 5)
res3

array([ 5, 10, 15, 20])

In [56]:
res3 = np.multiply(arr1, arr2)
res3

array([ 5, 12, 21, 32])

In [57]:
res4 = np.divide(arr1, 2)
res4

array([0.5, 1. , 1.5, 2. ])

In [58]:
res4 = np.divide(arr2, arr1)
res4

array([5.        , 3.        , 2.33333333, 2.        ])

In [59]:
res4[1]

3.0

In [60]:
a = np.array([[2,9],[6,13]])
b = np.array([[1,4],[3,11]])
a,b

(array([[ 2,  9],
        [ 6, 13]]),
 array([[ 1,  4],
        [ 3, 11]]))

In [61]:
'''Perform the following operations,
a. Cross product of A and B.
b. Dot product of A and B.
c. Matrix multiplication of A and B.
d. Square root of A and B.'''

'Perform the following operations,\na. Cross product of A and B.\nb. Dot product of A and B.\nc. Matrix multiplication of A and B.\nd. Square root of A and B.'

In [62]:
np.cross(a, b)

array([-1, 27])

In [63]:
np.dot(a,b)

array([[ 29, 107],
       [ 45, 167]])

In [64]:
A = [[6, 7],
      [8, 9]]
 
print(np.array(A) [0,0])

6


In [65]:
np.matmul(a, b)

array([[ 29, 107],
       [ 45, 167]])

In [66]:
np.sqrt(a)

array([[1.41421356, 3.        ],
       [2.44948974, 3.60555128]])

In [67]:
np.sqrt([a,b])

array([[[1.41421356, 3.        ],
        [2.44948974, 3.60555128]],

       [[1.        , 2.        ],
        [1.73205081, 3.31662479]]])

In [68]:
# Create a 3x3 matrix with random valus, flatten the array with the reshape() method and
# print the shape of the flattened array and the resultant array.

In [69]:
np.arange(1,10).reshape(3,3).reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [70]:
#ravel
np.ravel(np.arange(1,10).reshape(3,3))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
np.arange(1,10).reshape(3,3).reshape(1,9).reshape(-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [72]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3,3)
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [73]:
arr1 = np.random.randint(0, 100, size=9).reshape(3,3)
print(arr1)

[[61 78 92]
 [52 43 63]
 [98 45 83]]


In [74]:
'''5. Given two arrays A and B, perform the following operations
A = np.array([[2,3],[6,4]])
B = np.array([[3,6],[4,9]])
a. Horizontal stacking
b. Vertical Stacking
c. Row Stacking
d. Column Stacking
e. Depth Stacking
f. Append A to B
g. Concatenate A and B'''

'5. Given two arrays A and B, perform the following operations\nA = np.array([[2,3],[6,4]])\nB = np.array([[3,6],[4,9]])\na. Horizontal stacking\nb. Vertical Stacking\nc. Row Stacking\nd. Column Stacking\ne. Depth Stacking\nf. Append A to B\ng. Concatenate A and B'

In [75]:
A = np.array([[2,3],[6,4]])
B = np.array([[3,6],[4,9]])
A

array([[2, 3],
       [6, 4]])

In [76]:
print(np.datetime64('today', 'D'))

2022-04-24


In [77]:
dates_of_year = np.arange('2022-03', '2023-03', dtype='datetime64[D]')
dates_of_year

array(['2022-03-01', '2022-03-02', '2022-03-03', '2022-03-04',
       '2022-03-05', '2022-03-06', '2022-03-07', '2022-03-08',
       '2022-03-09', '2022-03-10', '2022-03-11', '2022-03-12',
       '2022-03-13', '2022-03-14', '2022-03-15', '2022-03-16',
       '2022-03-17', '2022-03-18', '2022-03-19', '2022-03-20',
       '2022-03-21', '2022-03-22', '2022-03-23', '2022-03-24',
       '2022-03-25', '2022-03-26', '2022-03-27', '2022-03-28',
       '2022-03-29', '2022-03-30', '2022-03-31', '2022-04-01',
       '2022-04-02', '2022-04-03', '2022-04-04', '2022-04-05',
       '2022-04-06', '2022-04-07', '2022-04-08', '2022-04-09',
       '2022-04-10', '2022-04-11', '2022-04-12', '2022-04-13',
       '2022-04-14', '2022-04-15', '2022-04-16', '2022-04-17',
       '2022-04-18', '2022-04-19', '2022-04-20', '2022-04-21',
       '2022-04-22', '2022-04-23', '2022-04-24', '2022-04-25',
       '2022-04-26', '2022-04-27', '2022-04-28', '2022-04-29',
       '2022-04-30', '2022-05-01', '2022-05-02', '2022-

In [78]:
arr2 = np.array([1,2,3,4,5])
arr2[arr2 > 3]

array([4, 5])

In [79]:
arr2 > 3

array([False, False, False,  True,  True])

In [80]:
arr2 = np.array([1,2,3,4,5,6,7,8,9])
x, y, z = np.array_split(arr2, 3)
x

array([1, 2, 3])

In [81]:
y

array([4, 5, 6])

In [82]:
x = np.hsplit(arr2, 3)

In [83]:
x

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]

In [84]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
x = np.vsplit(arr2, 3)

In [85]:
x

[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [86]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
y = x = np.hsplit(arr2, 3)

In [88]:
y

[array([[1],
        [4],
        [7]]),
 array([[2],
        [5],
        [8]]),
 array([[3],
        [6],
        [9]])]

In [89]:
j = np.array([[[2,3,4]]])
j

array([[[2, 3, 4]]])

In [90]:
j.reshape(1,3,1)

array([[[2],
        [3],
        [4]]])

In [100]:
A = np.array([[1,4,7],[3,1,9],[2,8,11]])
A

array([[ 1,  4,  7],
       [ 3,  1,  9],
       [ 2,  8, 11]])